
title: "Teliasec"
description: "Soluciones tecnol√≥gicas para tu empresa"
lang: "es"
url: "https://teliasec.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  # - jekyll-remote-theme
  # - jekyll-seo-tag
  # - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: false

author:
  name: "Teliasec"
  email: "info@teliasec.com"

exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
